spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/imagelite?sslmode=disable
    username: postgres
    password: postgress

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB


  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE